
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: slack-roller_development


test:
  <<: *default
  database: slack-roller_test


production:
  <<: *default
  database: slack-roller_production
  username: slack_roller
  password: <%= ENV['SLACK-ROLLER_DATABASE_PASSWORD'] %>
