# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 609aaba302423c339f2d2bfcf4a1dcfc15431b93eaaca6c71726fe92d640932602ec5f57eb0494ae2a5eaa762cecd712778f9122e138474df3328c4edb52d5a0

test:
  secret_key_base: a39bf3c40f4eecc925ab747c8763d5ddc8f499d5056ecca1705a0ee59e9c8e43ae14fb067545c54601eea8db8a35ce53845d13613a82576962f5bd99d99df771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
